// Add your code here
ddmake.motorRun(ddmake.Motors.M1, ddmake.Dir.CW, 100)
basic.pause(1000)
ddmake.motorRun(ddmake.Motors.M2, ddmake.Dir.CW, 100)
basic.pause(1000)
ddmake.motorRun(ddmake.Motors.All, ddmake.Dir.CW, 100)
basic.pause(1000)
ddmake.servoRun(ddmake.Servos.S1, 90)
basic.pause(1000)
ddmake.servoRun(ddmake.Servos.S2, 90)
basic.pause(1000)
ddmake.motorStop(ddmake.Motors.M1)
basic.pause(1000)
ddmake.motorStop(ddmake.Motors.M2)
basic.pause(1000)
ddmake.motorStop(ddmake.Motors.All)
basic.pause(1000)
ddmake.writeLED(ddmake.LED.LEDLeft,ddmake.LEDswitch.turnOn)
basic.pause(1000)
ddmake.writeLED(ddmake.LED.LEDLeft,ddmake.LEDswitch.turnOff)
basic.pause(1000)
ddmake.writeLED(ddmake.LED.LEDRight,ddmake.LEDswitch.turnOn )
basic.pause(1000)
ddmake.writeLED(ddmake.LED.LEDRight,ddmake.LEDswitch.turnOff)
serial.writeLine("L:" + ddmake.readPatrol(ddmake.Patrol.PatrolLeft))
basic.pause(1000)
serial.writeLine("R:" + ddmake.readPatrol(ddmake.Patrol.PatrolRight))
basic.pause(1000)
serial.writeLine("IR:" + ddmake.IR_read())
basic.pause(1000)
serial.writeLine("V:" + ddmake.IR_read_version())
basic.pause(1000)
serial.writeLine("CM:" + ddmake.Ultrasonic(PingUnit.Centimeters))
basic.pause(1000)

